# Application Name
spring.application.name=notification-service
server.port=8085

# Eureka Configuration
eureka.client.enabled=false

# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=notification_db
spring.data.mongodb.username=admin
spring.data.mongodb.password=password
spring.data.mongodb.authentication-database=admin

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=password

# RabbitMQ Queue/Exchange Names
rabbitmq.queue.name=notification.queue
rabbitmq.exchange.name=bookingExchange
rabbitmq.routing.key=booking.created

# Email Configuration (Mailtrap SMTP)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=763ef6ee65584c
spring.mail.password=80fc07800c033b
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Logging
logging.level.com.yeditepe.notificationservice=DEBUG
logging.level.org.springframework.amqp=DEBUG