spring.application.name=event-service
server.port=8082
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
spring.config.import=optional:configserver:http://config-server:8888/

spring.datasource.url=jdbc:h2:mem:eventdb
spring.datasource.username=sa
spring.datasource.password=
